WHITE=(255,255,255,255)
GRAY=(128,128,128,255)
BLACK=(0,0,0,255)
RED=(255,0,0,255)
GREEN=(0,255,0,255)
BLUE=(0,0,255,255)
YELLOW=(255,255,0,255)
MAGENTA=(255,0,255,255)
CYAN=(0,255,255,255)


levels = [
    {'num':'1','columns':[RED,GREEN,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[RED,YELLOW,MAGENTA],[YELLOW,GREEN,CYAN],[MAGENTA,CYAN,BLUE]],
    "msg":'Bem vindo!'},
    {'num':'2','columns':[YELLOW,RED,BLUE],'rows':[RED,BLUE ,YELLOW],
    'win':[[YELLOW,RED,MAGENTA],[WHITE,MAGENTA,BLUE],[YELLOW,YELLOW,WHITE]]},
    {'num':'3','columns':[RED,GREEN,BLUE,WHITE],'rows':[RED,GREEN,BLUE,WHITE],
    'win':[[BLACK,YELLOW,MAGENTA,WHITE],[YELLOW,BLACK,CYAN,WHITE],[MAGENTA,CYAN,BLACK,WHITE],[YELLOW,BLACK,CYAN,WHITE]]},
    {'num':'4','columns':[RED,GREEN,BLUE],'rows':[WHITE,BLACK,GRAY],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]},
    {'num':'5','columns':[RED,None,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]},
    {'num':'6','columns':[CYAN,YELLOW,MAGENTA],'rows':[CYAN,YELLOW,MAGENTA],
    'win':[[CYAN,GREEN,BLUE],[GREEN,YELLOW,RED],[BLUE,RED,MAGENTA]]},
    {'num':'7','columns':[RED,GREEN,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]},
    {'num':'8','columns':[RED,GREEN,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]},
    {'num':'9','columns':[RED,GREEN,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]},
    {'num':'10','columns':[RED,GREEN,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]},
    {'num':'11','columns':[RED,GREEN,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]},
    {'num':'12','columns':[RED,GREEN,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]},
    {'num':'13','columns':[RED,GREEN,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]},
    {'num':'14','columns':[RED,GREEN,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]},
    {'num':'15','columns':[RED,GREEN,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]},
    {'num':'16','columns':[RED,GREEN,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]},
    {'num':'17','columns':[RED,GREEN,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]},
    {'num':'18','columns':[RED,GREEN,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]},
    {'num':'19','columns':[RED,GREEN,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]},
    {'num':'20','columns':[RED,GREEN,BLUE],'rows':[RED,GREEN,BLUE],
    'win':[[BLACK,YELLOW,MAGENTA],[YELLOW,BLACK,CYAN],[MAGENTA,CYAN,BLACK]]}]